### ISSUE TITLE
API keys are hardcoded

### ISSUE THREAD

**Issue by LukeGotBored** [tychoyoung/MathGPT#1]
Hi there! Just a small heads up, you seem to have left both the OpenAI API key and the Discord bot token in main.py, you might want to remove them as they might get your OpenAI/Discord accounts banned, thanks!

**Comment by ZenoCoding** [comment]
Woah! I think I had disabled those keys a long time ago, but thanks for the heads-up! I'll remove them from the project, and since then have been using .env files to store all my tokens. Rookie mistake 😅

**Comment by ZenoCoding** [comment]
Hm, while I deleted them in the current files, the tokens still remain in commit history. What do you recommend I do?

**Comment by n3konet** [comment]
As long as the keys aren't valid anymore you should be alright! 
You can regenerate the Discord bot token via https://discord.com/developers 
(The old one won't be valid anymore after resetting it)
- select your bot 
- select the "Bot" tab on the left
- press "Reset Token"

The OpenAI key *should* be expired already, you can still disable it through the developer panel on their website

Also, before we wrap things up...
I just wanted to say how awesome this project is! Seriously, Keep up the great work :)
